# Generated by Django 4.2.5 on 2023-09-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_team_manager',
            field=models.BooleanField(default=False, verbose_name='team manager'),
        ),
    ]
