# Generated by Django 4.2.5 on 2023-09-19 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('status', models.CharField(choices=[('empty', 'empty'), ('full', 'full')], default='empty', max_length=10, verbose_name='status')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacity')),
            ],
            options={
                'verbose_name': 'MeetingRoom',
                'verbose_name_plural': 'MeetingRooms',
            },
        ),
    ]
