# Generated by Django 4.2.5 on 2023-09-19 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('is_empty', models.BooleanField(default=True, verbose_name='is empty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.room', verbose_name='room')),
            ],
            options={
                'verbose_name': 'Room Slot',
                'verbose_name_plural': 'Room Slots',
            },
        ),
    ]
