# Generated by Django 4.2.5 on 2023-09-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_roomslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name='is_active'),
        ),
    ]
