# Generated by Django 4.2.5 on 2023-09-25 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_remove_room_status_room_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomslot',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='roomslot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='start time'),
        ),
    ]
